

/**
 * This class is generated by the Netbeans IDE, * and registers all REST root resources created in the project. * Please, DO NOT EDIT this class !
 */
@javax.ws.rs.ApplicationPath("app")
public class ApplicationConfig extends javax.ws.rs.core.Application {
}